version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: nestjs_template_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nestjs_template_db']
      interval: 5s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - '1883:1883'
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

volumes:
  postgres_data:
